backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images"

collections:
  - name: "standards"
    label: "Standards"
    folder: "standards"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "main-aside" }
      - { label: "Page title", name: "title", widget: "string" }
      - { label: "Meta desc", name: "desc", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Page heading", name: "pageTitle", widget: "string" }
      - { label: "Taxonomy", name: "pageTaxonomy", widget: "hidden", default: "content" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "standard" }
      - { label: "Extract", name: "extract", width: "string" }
      - { label: "The modifier", name: "themeModifier", widget: hidden, default: "standards" }
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Navigation"
        name: "eleventyNavigation"
        widget: object
        fields:
          - { label: "Key", name: "key", widget: string, default: "{{title}}" }
          - { label: "Parent", name: "parent", widget: string, default: "Standards" }
